version: '3'
services:
 mariadb:
   container_name: mariadb
   image: mariadb:latest
   restart: always
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=jgklsdfjkl
     - MYSQL_DATABASE=projectdb
     - MYSQL_USER=user
     - MYSQL_PASSWORD=hjklhkjh
   volumes:
     - db-data:/var/lib/mysql 
volumes:
  db-data:
  pg-db-data:
